version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
    install:
      runtime-versions:
        nodejs: 16
      on-failure: ABORT
      commands:
        - |
          npm install
    build:
      on-failure: ABORT
      commands: 
        - |
          npm run build:about
    post_build:
      on-failure: ABORT
      commands:
        - |
          aws s3 cp dist s3://${DEPLOY_S3}  --recursive 
          aws cloudfront create-invalidation --distribution-id E1P0IZ5LAI7MXS --paths "/about/index.html"
