version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - npm run test

batch:
  fast-fail: true 
  build-graph:
    - identifier: test_phase
    - identifier: home_page_build
      buildspec: buildspec.home.yml
      depend-on:
        - test_phase
    - identifier: about_page_build
      buildspec: buildspec.about.yml
      depend-on:
        - test_phase