version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
    install:
      runtime-versions:
        nodejs: 16
      on-failure: ABORT
      commands:
        - |
          if [[ ($GITHUB_EVENT_NAME == "push") ]]; then 
            npm install
          fi
    build:
      on-failure: ABORT
      commands:
        - |
          if [[ ($GITHUB_EVENT_NAME == "push") ]]; then 
            npm run build:home
          fi
    post_build:
      on-failure: ABORT
      commands:
        - |
          if [[ ($GITHUB_EVENT_NAME == "push") ]]; then 
            aws s3 cp dist s3://${DEPLOY_S3}  --recursive 
            aws cloudfront create-invalidation --distribution-id E1FHG4YJG6RWZT --paths "/home/index.html"
          fi
