version: 0.2

batch:
  fast-fail: true 
  build-list:
    - identifier: home_page_build
      buildspec: buildspec.deploy.home.yml
    - identifier: about_page_build
      buildspec: buildspec.deploy.about.yml