version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

batch:
  build-graph:
    - identifier: initial_build
    - identifier: home_page_build
      buildspec: buildspec.deploy.home.yml
      depend-on:
        - initial_build
    - identifier: about_page_build
      buildspec: buildspec.deploy.about.yml
      depend-on:
        - initial_build