version: 0.2

env:
  shell: bash

phases:
   install:
      on-failure: ABORT
      commands: 
        - |
          printenv

batch:
  build-graph:
    - identifier: initial_build
    - identifier: home_page_build
      buildspec: buildspec.pullrequest.home.yml
      depend-on:
        - initial_build
    - identifier: about_page_build
      buildspec: buildspec.pullrequest.about.yml
      depend-on:
        - initial_build