version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash
  secrets-manager:
    GITHUB_ACCESS_TOKEN: GITHUB_PERSONAL_ACCESS_TOKEN:value

phases:
    build:
      on-failure: ABORT
      commands:
        - |
          npm run build:home
