version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash
  secrets-manager:
    GITHUB_ACCESS_TOKEN: GITHUB_PERSONAL_ACCESS_TOKEN:value

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - | 
<<<<<<< Updated upstream
        printenv
        node scripts/install.js
=======
        node scripts/pullRequest/install.js
>>>>>>> Stashed changes
  pre_build:
    on-failure: ABORT
    commands:
      - |
        npm run test