version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo "do some test in pre_build phase"

batch:
    fast-fail: true 
    build-graph:
    - identifier: install-phase
    - identifier: home-page-build
      buildspec: buildspec.home.yml
      depend-on:
        - install-phase
    - identifier: about-page-build
      buildspec: buildspec.about.yml
      depend-on:
        - install-phase