version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
    build:
      on-failure: ABORT
      commands:
        - |
          npm run build:home
    post_build:
      on-failure: ABORT
      commands:
        - | 
          aws s3 cp dist s3://${DEPLOY_S3}  --recursive 
          aws cloudfront create-invalidation --distribution-id EFSPLA2Q26I8Z --paths "/home/index.html"
