version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "do some test in pre_build phase"

batch:
  fast-fail: true 
  build-graph:
    - identifier: install_phase
    - identifier: home_page_build
      buildspec: buildspec.home.yml
      depend-on:
        - install_phase
    - identifier: about_page_build
      buildspec: buildspec.about.yml
      depend-on:
        - install_phase