version: 0.2

batch:
  build-graph:
    - identifier: initial_build
    - identifier: home_page_build
      buildspec: codebuild/buildspec.deploy.home.yml
      depend-on:
        - initial_build
    - identifier: about_page_build
      buildspec: codebuild/buildspec.deploy.about.yml
      depend-on:
        - initial_build