version: 0.2

cache:
  paths:
    - 'node_modules/**/*'

env:
  shell: bash
  secrets-manager:
    GITHUB_ACCESS_TOKEN: GITHUB_PERSONAL_ACCESS_TOKEN:value

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - | 
        SHOULD_REINSTALL_NODE_MODULES=$(node scripts/pullRequest/install.js)
        if [ $SHOULD_REINSTALL_NODE_MODULES = true ]; then
          yarn
        fi
  build:
    on-failure: ABORT
    commands:
      - yarn build:home
