version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash
  secrets-manager:
    GITHUB_ACCESS_TOKEN: GITHUB_PERSONAL_ACCESS_TOKEN:value

phases:
    install:
      runtime-versions:
        nodejs: 16
      on-failure: ABORT
      commands:
        - |
          yarn --version
          . scripts/pullRequest/install.sh
    build:
      on-failure: ABORT
      commands:
        - |
          npm run build:about
