version: 0.2

cache:
  paths:
    - 'node_modules/**/*'

env:
  shell: bash

phases:  
    install:
      runtime-versions:
        nodejs: 16
      on-failure: ABORT
      commands:
        - | 
          SHOULD_REINSTALL_NODE_MODULES=$(node scripts/deploy/install.js)
          if [ $SHOULD_REINSTALL_NODE_MODULES = true ]; then
            yarn
          fi
    build:
      on-failure: ABORT
      commands: 
        - yarn build:about
    post_build:
      on-failure: ABORT
      commands:
        - aws s3 cp dist s3://${DEPLOY_S3}  --recursive 
        - aws sts assume-role --role-arn arn:aws:iam::171191418924:role/cdnInvalidationIamRole-CdnValidationRole-R024WEOGFWL9 --role-session-name TempCdnValidationRole
        - aws cloudfront create-invalidation --distribution-id E3HZOT1NNRJHM --paths "/about/index.html"
